---
title: "projectfinish"
author: "Ricardo Andrés Rojas Rico & José Manuel Mendoza Vásquez"
date: "2023-06-08"
output: html_document
---

# INTRODUCCIÓN

En este estudio, exploraremos la relación entre la altura y la edad en las personas. Utilizando técnicas estadísticas y probabilísticas, buscaremos predecir la altura en función de la edad y viceversa. Estos hallazgos nos permitirán obtener información valiosa sobre cómo la edad puede influir en la altura y viceversa. Este conocimiento puede tener aplicaciones prácticas en áreas como la medicina y la nutrición, así como en el desarrollo de modelos más precisos para estimar estas características físicas.

# Objetivo general:

* Analizar la relación entre la altura y la edad en las personas, utilizando técnicas estadísticas y probabilísticas, con el fin de predecir la altura en función de la edad y viceversa.

# Objetivos específicos:

1. Recolectar una muestra representativa de datos de altura y edad de personas de diferentes grupos de edad.
2. Aplicar técnicas estadísticas y modelos probabilísticos para analizar la correlación entre la altura y la edad.
3. Desarrollar un modelo predictivo que permita estimar la altura en base a la edad y viceversa, con un margen de error aceptable.


```{r}
file <- "C:/Users/rojas/OneDrive/Escritorio/proyectofinalR/db.txt"

datos <- read.table(file=file, header=TRUE)
# head(datos, n=18) # shows the first 6 rows   

altura <- read.table(file=file, header = TRUE)
names(altura)


pairs(altura)

cor(altura)
regresion <- lm(edad ~ altura, data = datos)
summary(regresion)

plot(altura$edad, altura$altura, xlab='Edad', ylab='Altura')
abline(regresion)

# El coeficiente de determinación (es decir, el coeficiente de correlación al cuadrado) mide la bondad del ajuste de la recta a los datos. A partir de la salida anterior, vemos que su valor en este caso es Multiple R-squared: 0.701.
confint(regresion)

# La tabla de análisis de la varianza de los errores se obtiene con el comando anova:
anova(regresion)


residuos <- rstandard(regresion)
valores.ajustados <- fitted(regresion)
plot(valores.ajustados, residuos)


# No se observa ningún patrón especial, por lo que tanto la homocedasticidad como la linealidad resultan hipótesis razonables.

# La hipótesis de normalidad se suele comprobar mediante un QQ plot de los residuos. El siguiente código sirve para obtenerlo:

qqnorm(residuos)
qqline(residuos)
# Dado que los puntos están bastante alineados, la normalidad también parece aceptable.
```

